DELIMITER $$
CREATE SCHEMA 'LogsDatabase';

CREATE TABLE 'LogsDatabase'.'Logs'(
'LogID' INT NOT NULL auto_increment,
'LogDate' DATETIME NOT NULL,
'Description' TEXT,
PRIMARY KEY('LogID')
)
PARTITION BY RANGE(YEAR(LogDate))
PARTITION p1 LESS THAN(1990),
PARTITION p2 LESS THAN(2000),
PARTITION p3 LESS THAN(2010)

CREATE PROCEDURE InsertData
BEGIN
DECLARE index INT;
SET index = 0;
START TRANSACTION
WHILE index <= 1000000 DO
	INSERT INTO 'Logs'('LogDate','Description')
VALUES(CAST(FLOOR(1000000 + RAND(8999999) AS VARCHAR),FROM_UNIXTIME(
        UNIX_TIMESTAMP('2010-04-30 14:53:27') + FLOOR(0 + (RAND() * 63072000))
    ));
SET index = index + 1;
END WHILE;
COMMIT
DELIMITER;
