//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeGetterConsoleClient.DateTimeGetterConsumer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DateTimeGetterConsumer.IDateTimeGetter")]
    public interface IDateTimeGetter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateTimeGetter/GetDateGetDayOfWeek", ReplyAction="http://tempuri.org/IDateTimeGetter/GetDateGetDayOfWeekResponse")]
        string GetDateGetDayOfWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateTimeGetter/GetDateGetDayOfWeek", ReplyAction="http://tempuri.org/IDateTimeGetter/GetDateGetDayOfWeekResponse")]
        System.Threading.Tasks.Task<string> GetDateGetDayOfWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDateTimeGetterChannel : DateTimeGetterConsoleClient.DateTimeGetterConsumer.IDateTimeGetter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DateTimeGetterClient : System.ServiceModel.ClientBase<DateTimeGetterConsoleClient.DateTimeGetterConsumer.IDateTimeGetter>, DateTimeGetterConsoleClient.DateTimeGetterConsumer.IDateTimeGetter {
        
        public DateTimeGetterClient() {
        }
        
        public DateTimeGetterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DateTimeGetterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateTimeGetterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateTimeGetterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDateGetDayOfWeek(System.DateTime date) {
            return base.Channel.GetDateGetDayOfWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDateGetDayOfWeekAsync(System.DateTime date) {
            return base.Channel.GetDateGetDayOfWeekAsync(date);
        }
    }
}
